export const MODE = {
  DESKTOP: "DESKTOP",
  MOBILE: "MOBILE",
};

export const STATUS = {
  STAND_BY: "STAND_BY",
  SEARCHING: "SEARCHING",
  PENDING: "PENDING",
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
};
